version: '3.8'

services:
  db:
    image: mysql:8.0.19
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'Cinema'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'

volumes:
  my-db:
